# Generated by Django 6.0.1 on 2026-01-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poetry',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
