# Generated by Django 6.0.1 on 2026-01-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0002_poetry_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poetry',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
